//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebServiceDummyNewCallCenter
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntitiesCallCenter : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntitiesCallCenter usando la cadena de conexión encontrada en la sección 'EntitiesCallCenter' del archivo de configuración de la aplicación.
        /// </summary>
        public EntitiesCallCenter() : base("name=EntitiesCallCenter", "EntitiesCallCenter")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesCallCenter.
        /// </summary>
        public EntitiesCallCenter(string connectionString) : base(connectionString, "EntitiesCallCenter")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesCallCenter.
        /// </summary>
        public EntitiesCallCenter(EntityConnection connection) : base(connection, "EntitiesCallCenter")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CallCenter> CallCenter
        {
            get
            {
                if ((_CallCenter == null))
                {
                    _CallCenter = base.CreateObjectSet<CallCenter>("CallCenter");
                }
                return _CallCenter;
            }
        }
        private ObjectSet<CallCenter> _CallCenter;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CallCenter. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCallCenter(CallCenter callCenter)
        {
            base.AddObject("CallCenter", callCenter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GJDummyModel", Name="CallCenter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CallCenter : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CallCenter.
        /// </summary>
        /// <param name="idCase">Valor inicial de la propiedad IdCase.</param>
        public static CallCenter CreateCallCenter(global::System.Int32 idCase)
        {
            CallCenter callCenter = new CallCenter();
            callCenter.IdCase = idCase;
            return callCenter;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCase
        {
            get
            {
                return _IdCase;
            }
            set
            {
                if (_IdCase != value)
                {
                    OnIdCaseChanging(value);
                    ReportPropertyChanging("IdCase");
                    _IdCase = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCase");
                    OnIdCaseChanged();
                }
            }
        }
        private global::System.Int32 _IdCase;
        partial void OnIdCaseChanging(global::System.Int32 value);
        partial void OnIdCaseChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreEvento
        {
            get
            {
                return _NombreEvento;
            }
            set
            {
                OnNombreEventoChanging(value);
                ReportPropertyChanging("NombreEvento");
                _NombreEvento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreEvento");
                OnNombreEventoChanged();
            }
        }
        private global::System.String _NombreEvento;
        partial void OnNombreEventoChanging(global::System.String value);
        partial void OnNombreEventoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumRadicado
        {
            get
            {
                return _NumRadicado;
            }
            set
            {
                OnNumRadicadoChanging(value);
                ReportPropertyChanging("NumRadicado");
                _NumRadicado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumRadicado");
                OnNumRadicadoChanged();
            }
        }
        private global::System.String _NumRadicado;
        partial void OnNumRadicadoChanging(global::System.String value);
        partial void OnNumRadicadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroRadicadoTramite
        {
            get
            {
                return _NumeroRadicadoTramite;
            }
            set
            {
                OnNumeroRadicadoTramiteChanging(value);
                ReportPropertyChanging("NumeroRadicadoTramite");
                _NumeroRadicadoTramite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroRadicadoTramite");
                OnNumeroRadicadoTramiteChanged();
            }
        }
        private global::System.String _NumeroRadicadoTramite;
        partial void OnNumeroRadicadoTramiteChanging(global::System.String value);
        partial void OnNumeroRadicadoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumIdentificacion
        {
            get
            {
                return _NumIdentificacion;
            }
            set
            {
                OnNumIdentificacionChanging(value);
                ReportPropertyChanging("NumIdentificacion");
                _NumIdentificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumIdentificacion");
                OnNumIdentificacionChanged();
            }
        }
        private global::System.String _NumIdentificacion;
        partial void OnNumIdentificacionChanging(global::System.String value);
        partial void OnNumIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoIdentificacion
        {
            get
            {
                return _TipoIdentificacion;
            }
            set
            {
                OnTipoIdentificacionChanging(value);
                ReportPropertyChanging("TipoIdentificacion");
                _TipoIdentificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoIdentificacion");
                OnTipoIdentificacionChanged();
            }
        }
        private global::System.String _TipoIdentificacion;
        partial void OnTipoIdentificacionChanging(global::System.String value);
        partial void OnTipoIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimerNombre
        {
            get
            {
                return _PrimerNombre;
            }
            set
            {
                OnPrimerNombreChanging(value);
                ReportPropertyChanging("PrimerNombre");
                _PrimerNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimerNombre");
                OnPrimerNombreChanged();
            }
        }
        private global::System.String _PrimerNombre;
        partial void OnPrimerNombreChanging(global::System.String value);
        partial void OnPrimerNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SegundoNombre
        {
            get
            {
                return _SegundoNombre;
            }
            set
            {
                OnSegundoNombreChanging(value);
                ReportPropertyChanging("SegundoNombre");
                _SegundoNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SegundoNombre");
                OnSegundoNombreChanged();
            }
        }
        private global::System.String _SegundoNombre;
        partial void OnSegundoNombreChanging(global::System.String value);
        partial void OnSegundoNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimerApellido
        {
            get
            {
                return _PrimerApellido;
            }
            set
            {
                OnPrimerApellidoChanging(value);
                ReportPropertyChanging("PrimerApellido");
                _PrimerApellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimerApellido");
                OnPrimerApellidoChanged();
            }
        }
        private global::System.String _PrimerApellido;
        partial void OnPrimerApellidoChanging(global::System.String value);
        partial void OnPrimerApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SegundoApellido
        {
            get
            {
                return _SegundoApellido;
            }
            set
            {
                OnSegundoApellidoChanging(value);
                ReportPropertyChanging("SegundoApellido");
                _SegundoApellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SegundoApellido");
                OnSegundoApellidoChanged();
            }
        }
        private global::System.String _SegundoApellido;
        partial void OnSegundoApellidoChanging(global::System.String value);
        partial void OnSegundoApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefonoMovil
        {
            get
            {
                return _TelefonoMovil;
            }
            set
            {
                OnTelefonoMovilChanging(value);
                ReportPropertyChanging("TelefonoMovil");
                _TelefonoMovil = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefonoMovil");
                OnTelefonoMovilChanged();
            }
        }
        private global::System.String _TelefonoMovil;
        partial void OnTelefonoMovilChanging(global::System.String value);
        partial void OnTelefonoMovilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefonoFijo
        {
            get
            {
                return _TelefonoFijo;
            }
            set
            {
                OnTelefonoFijoChanging(value);
                ReportPropertyChanging("TelefonoFijo");
                _TelefonoFijo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefonoFijo");
                OnTelefonoFijoChanged();
            }
        }
        private global::System.String _TelefonoFijo;
        partial void OnTelefonoFijoChanging(global::System.String value);
        partial void OnTelefonoFijoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tramite
        {
            get
            {
                return _Tramite;
            }
            set
            {
                OnTramiteChanging(value);
                ReportPropertyChanging("Tramite");
                _Tramite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tramite");
                OnTramiteChanged();
            }
        }
        private global::System.String _Tramite;
        partial void OnTramiteChanging(global::System.String value);
        partial void OnTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTramite
        {
            get
            {
                return _SubTramite;
            }
            set
            {
                OnSubTramiteChanging(value);
                ReportPropertyChanging("SubTramite");
                _SubTramite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTramite");
                OnSubTramiteChanged();
            }
        }
        private global::System.String _SubTramite;
        partial void OnSubTramiteChanging(global::System.String value);
        partial void OnSubTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
    }

    #endregion
    
}
