//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colpensiones2GJ.CapaSOAQueryForm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CapaSOAQueryForm.QueryFormSOASoap")]
    public interface QueryFormSOASoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode QueryCases(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode QueryEntities(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCasesAsString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryCasesAsString(string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryEntitiesAsString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryEntitiesAsString(string sxml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryFormSOASoapChannel : Colpensiones2GJ.CapaSOAQueryForm.QueryFormSOASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryFormSOASoapClient : System.ServiceModel.ClientBase<Colpensiones2GJ.CapaSOAQueryForm.QueryFormSOASoap>, Colpensiones2GJ.CapaSOAQueryForm.QueryFormSOASoap {
        
        public QueryFormSOASoapClient() {
        }
        
        public QueryFormSOASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryFormSOASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryFormSOASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryFormSOASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode QueryCases(System.Xml.XmlNode xml) {
            return base.Channel.QueryCases(xml);
        }
        
        public System.Xml.XmlNode QueryEntities(System.Xml.XmlNode xml) {
            return base.Channel.QueryEntities(xml);
        }
        
        public string QueryCasesAsString(string sxml) {
            return base.Channel.QueryCasesAsString(sxml);
        }
        
        public string QueryEntitiesAsString(string sxml) {
            return base.Channel.QueryEntitiesAsString(sxml);
        }
    }
}
